FROM golang:latest
RUN mkdir /go/src/app
ADD . /go/src/app/
WORKDIR /go/src/app

ENV GOPATH /go

RUN go get -u github.com/golang/dep/...
RUN dep ensure

RUN go build -o main .
EXPOSE 3000
CMD ["/go/src/app/main"]